### ISSUE TITLE
custom exception

### ISSUE THREAD

**Issue by Dhaiven** [Dhaiven/BetterMaths#2]
When we do `bm.Equation("pi!").result()`, there is this error:
```
Traceback (most recent call last):
  File "\\srv1-2019\hdebelle$\Documents\GitHub\Bac-Pratique\test.py", line 4, in <module>
    print(bm.Equation("pi!").result())
  File "C:\Users\hdebelle.RESOEDU\AppData\Roaming\Python\Python310-32\site-packages\BetterMaths\main.py", line 279, in 
result
    return self.__resolve__(self.equation)
  File "C:\Users\hdebelle.RESOEDU\AppData\Roaming\Python\Python310-32\site-packages\BetterMaths\main.py", line 367, in 
__resolve__
    return self.__resolve__(equation[:start - len(mustBeFactorial)] + str(math.factorial(int(mustBeFactorial))) + equation[start + 1:])
ValueError: invalid literal for int() with base 10: ''
```

It's normal because pi is an float number and factorial accept only integer number.
But must be return custom exception like this:
```
ValueError: invalid expression pi!, factorial must be an int

**Comment by Dhaiven** [comment]
Fixed for factorial but not for entire errors
